### ISSUE TITLE
You seem to need a Korean translation work.

### ISSUE THREAD

**Issue by yoonbincho** [QuentinNev/AngryWirds#1]
I am a software engineering professor interested in game production. You can help to translate into Korean. Do I need it?

**Comment by QuentinNev** [comment]
I'm not sure what you're offering to me.
Do you need help to translate something or do you offer to translate my game in Korean ?
In either cases I have to decline, it's only a school project and I'm busy on other projects.
But thank you for the offer, I hope you'll find what you're looking for.

Oh and don't forget to say hi ! :)
